events {}

http {
    server {
        listen 80;

        # chall-01 roda diretamente na porta 9099 — sem proxy aqui

        location /chall-02/ {
            proxy_pass http://chall-02:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /chall-03/ {
            proxy_pass http://chall-03:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /chall-04/ {
            proxy_pass http://chall-04:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /chall-05/ {
            proxy_pass http://chall-05:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /chall-06/ {
            proxy_pass http://chall-06:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            # X-Forwarded-For do cliente é passado sem modificação (vulnerabilidade intencional)
        }

        location /chall-07/ {
            proxy_pass http://chall-07:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /chall-08/ {
            proxy_pass http://chall-08:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /chall-09/ {
            proxy_pass http://chall-09:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /chall-10/ {
            proxy_pass http://chall-10:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /chall-11/ {
            proxy_pass http://chall-11:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # CTFd — catch-all, fica por último
        location / {
            proxy_pass http://ctfd:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 300;
        }
    }
}
